on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Deploy
jobs:
  production:
    name: Upload Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload Production
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: rish_ida_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
        env:
          FTP_SERVER: ${{ secrets.SSH_HOST }}
          FTP_USERNAME: ${{ secrets.SSH_USERNAME }}
          LOCAL_DIR: ./
          REMOTE_DIR: /var/www/html/media.rish/wp/
