on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Deploy
jobs:
  production:
    name: Upload Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install SSH key
        run: |
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           name: rish_ida_rsa
           known_hosts: ${{ secrets.KNOWN_HOSTS }}
#          mkdir -p ~/.ssh/
#          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/rish_ida_rsa
#          chmod 600 ~/.ssh/rish_ida_rsa
      - name: Deploy
        run: rsync -ahvz -e "ssh -i ~/.ssh/rish_ida_rsa -p ${{ secrets.SSH_PORT }} ./ ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}:/var/www/html/media.rishry/wp/
#        uses: shimataro/ssh-key-action@v2
#        with:
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          name: rish_ida_rsa
#          known_hosts: ${{ secrets.KNOWN_HOSTS }}
#        env:
#          SSH_HOST: ${{ secrets.SSH_HOST }}
#          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
#          SSH_PORT: ${{ secrets.SSH_PORT }}
#          LOCAL_DIR: ./
#          REMOTE_DIR: /var/www/html/media.rishry/wp/
