on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
name: Deploy
jobs:
  production:
    name: Upload Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: rish_ida_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          LOCAL_DIR: ./
          REMOTE_DIR: /var/www/html/media.rish/
